In [58]:
# importing libraries
# the following libraries were used for data manipulation preprocessing and analysis
# pandas for loading and cleaning and transformation, numpy for numerical operations.
import pandas as pd 
import numpy as np
import os
os.getcwd()

'c:\\Users\\fouzi\\OneDrive\\Desktop\\AirFly-Insights'

In [ ]:
# AirFly Insights – Week 1

## Project Goal
# Analyze airline operational performance to understand delay patterns and cancellation trends.

## Workflow
'''1. Load dataset
2. Explore structure
3. Check missing values
4. Perform sampling
5. Optimize memory'''

In [ ]:
# Dataset Loading
df=pd.read_csv("C:/Users/fouzi/OneDrive/Desktop/AirFly-Insights/Data/Raw/2018.csv/2018.csv",nrows=200000)
print(df.head())

      FL_DATE OP_CARRIER  OP_CARRIER_FL_NUM ORIGIN DEST  CRS_DEP_TIME  \
0  2018-01-01         UA               2429    EWR  DEN          1517
1  2018-01-01         UA               2427    LAS  SFO          1115
2  2018-01-01         UA               2426    SNA  DEN          1335
3  2018-01-01         UA               2425    RSW  ORD          1546
4  2018-01-01         UA               2424    ORD  ALB           630

   DEP_TIME  DEP_DELAY  TAXI_OUT  WHEELS_OFF  ...  CRS_ELAPSED_TIME  \
0    1512.0       -5.0      15.0      1527.0  ...             268.0
1    1107.0       -8.0      11.0      1118.0  ...              99.0
2    1330.0       -5.0      15.0      1345.0  ...             134.0
3    1552.0        6.0      19.0      1611.0  ...             190.0
4     650.0       20.0      13.0       703.0  ...             112.0

   ACTUAL_ELAPSED_TIME  AIR_TIME  DISTANCE  CARRIER_DELAY  WEATHER_DELAY  \
0                250.0     225.0    1605.0            NaN            NaN
1                 83.0      65.0     414.0            NaN            NaN
2                126.0     106.0     846.0            NaN            NaN
3                182.0     157.0    1120.0            NaN            NaN
4                106.0      83.0     723.0            NaN            NaN

  NAS_DELAY  SECURITY_DELAY  LATE_AIRCRAFT_DELAY  Unnamed: 27
0       NaN             NaN                  NaN          NaN
1       NaN             NaN                  NaN          NaN
2       NaN             NaN                  NaN          NaN
3       NaN             NaN                  NaN          NaN
4       NaN             NaN                  NaN          NaN

[5 rows x 28 columns]

In [ ]:
## Understanding Dataset Size Using df.shape(rows,cols)
df.shape

(200000, 28)

In [ ]:
# exploring  columns name
df.columns

Index(['FL_DATE', 'OP_CARRIER', 'OP_CARRIER_FL_NUM', 'ORIGIN', 'DEST',
       'CRS_DEP_TIME', 'DEP_TIME', 'DEP_DELAY', 'TAXI_OUT', 'WHEELS_OFF',
       'WHEELS_ON', 'TAXI_IN', 'CRS_ARR_TIME', 'ARR_TIME', 'ARR_DELAY',
       'CANCELLED', 'CANCELLATION_CODE', 'DIVERTED', 'CRS_ELAPSED_TIME',
       'ACTUAL_ELAPSED_TIME', 'AIR_TIME', 'DISTANCE', 'CARRIER_DELAY',
       'WEATHER_DELAY', 'NAS_DELAY', 'SECURITY_DELAY', 'LATE_AIRCRAFT_DELAY',
       'Unnamed: 27'],
      dtype='object')

In [ ]:
# selecting relevent columns for analysis after loadings the df selecting required cols
selected_cols=["FL_DATE","OP_CARRIER","ORIGIN","DEST","CRS_DEP_TIME","DEP_TIME","DEP_DELAY",
               "ARR_TIME","ARR_DELAY","CANCELLED","CANCELLATION_CODE","DISTANCE","CRS_DEP_TIME","CRS_ARR_TIME","TAXI_IN","TAXI_OUT"]
df=df[selected_cols]
df.shape

(200000, 16)

In [ ]:
# inspecting the data structure using
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 16 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   FL_DATE            200000 non-null  object
 1   OP_CARRIER         200000 non-null  object
 2   ORIGIN             200000 non-null  object
 3   DEST               200000 non-null  object
 4   CRS_DEP_TIME       200000 non-null  int64
 5   DEP_TIME           191257 non-null  float64
 6   DEP_DELAY          191035 non-null  float64
 7   ARR_TIME           190937 non-null  float64
 8   ARR_DELAY          190442 non-null  float64
 9   CANCELLED          200000 non-null  float64
 10  CANCELLATION_CODE  8905 non-null    object
 11  DISTANCE           200000 non-null  float64
 12  CRS_DEP_TIME       200000 non-null  int64
 13  CRS_ARR_TIME       200000 non-null  int64
 14  TAXI_IN            190937 non-null  float64
 15  TAXI_OUT           191153 non-null  float64
dtypes: float64(8), int64(3), object(5)
memory usage: 24.4+ MB

In [ ]:
# formating Date column
df['FL_DATE ']=pd.to_datetime(df['FL_DATE'])

In [ ]:
# checking for null values and sum of null
df.isnull().sum()

FL_DATE                   0
OP_CARRIER                0
ORIGIN                    0
DEST                      0
CRS_DEP_TIME              0
DEP_TIME               8743
DEP_DELAY              8965
ARR_TIME               9063
ARR_DELAY              9558
CANCELLED                 0
CANCELLATION_CODE    191095
DISTANCE                  0
CRS_DEP_TIME              0
CRS_ARR_TIME              0
TAXI_IN                9063
TAXI_OUT               8847
FL_DATE                   0
dtype: int64

In [ ]:
# checking % of null values analysis
(df.isnull().sum()/len(df))*100

FL_DATE               0.0000
OP_CARRIER            0.0000
ORIGIN                0.0000
DEST                  0.0000
CRS_DEP_TIME          0.0000
DEP_TIME              4.3715
DEP_DELAY             4.4825
ARR_TIME              4.5315
ARR_DELAY             4.7790
CANCELLED             0.0000
CANCELLATION_CODE    95.5475
DISTANCE              0.0000
CRS_DEP_TIME          0.0000
CRS_ARR_TIME          0.0000
TAXI_IN               4.5315
TAXI_OUT              4.4235
FL_DATE               0.0000
dtype: float64

In [ ]:
#  droping the high % of null values columns
df=df.drop(columns=['CANCELLATION_CODE'])

In [ ]:
# columns
df.columns

Index(['FL_DATE', 'OP_CARRIER', 'ORIGIN', 'DEST', 'CRS_DEP_TIME', 'DEP_TIME',
       'DEP_DELAY', 'ARR_TIME', 'ARR_DELAY', 'CANCELLED', 'DISTANCE',
       'CRS_DEP_TIME', 'CRS_ARR_TIME', 'TAXI_IN', 'TAXI_OUT', 'FL_DATE '],
      dtype='object')

In [ ]:
# checking the % analysis again after removed columns
(df.isnull().sum()/len(df))*100

FL_DATE         0.0000
OP_CARRIER      0.0000
ORIGIN          0.0000
DEST            0.0000
CRS_DEP_TIME    0.0000
DEP_TIME        4.3715
DEP_DELAY       4.4825
ARR_TIME        4.5315
ARR_DELAY       4.7790
CANCELLED       0.0000
DISTANCE        0.0000
CRS_DEP_TIME    0.0000
CRS_ARR_TIME    0.0000
TAXI_IN         4.5315
TAXI_OUT        4.4235
FL_DATE         0.0000
dtype: float64

In [ ]:
# filtering the cancelled flights 0=flights was not cancel,1=flights cancelled
df["CANCELLED"].value_counts()

CANCELLED
0.0    191095
1.0      8905
Name: count, dtype: int64

In [ ]:
# after filtering using independent df for removing cancelled flights
df=df[df['CANCELLED']==0].copy()

In [15]:
df.shape

(191095, 16)

In [ ]:
#  again checking %
(df.isnull().sum()/len(df))*100

FL_DATE         0.000000
OP_CARRIER      0.000000
ORIGIN          0.000000
DEST            0.000000
CRS_DEP_TIME    0.000000
DEP_TIME        0.000000
DEP_DELAY       0.113033
ARR_TIME        0.082681
ARR_DELAY       0.341715
CANCELLED       0.000000
DISTANCE        0.000000
CRS_DEP_TIME    0.000000
CRS_ARR_TIME    0.000000
TAXI_IN         0.082681
TAXI_OUT        0.000000
FL_DATE         0.000000
dtype: float64

In [ ]:
# memory optimization
df.memory_usage(deep=True).sum()/1024**2

np.float64(57.953081130981445)

In [ ]:
# converting date column properly
df['FL_DATE']=pd.to_datetime(df['FL_DATE'])

In [ ]:
# convering category cols
df['OP_CARRIER'] = df['OP_CARRIER'].astype('category')
df['ORIGIN'] = df['ORIGIN'].astype('category')
df['DEST'] = df['DEST'].astype('category')

In [ ]:
# reduce numeric precision  instead of float64_ used 32
float_cols = ['DEP_DELAY', 'ARR_DELAY', 'TAXI_OUT', 'TAXI_IN']

for col in float_cols:
    df[col] = df[col].astype('float32')

In [21]:
df.memory_usage(deep=True).sum()/1024**2

np.float64(18.456738471984863)

In [ ]:
# understanding the patterns and statistical distribution
df.describe()

,FL_DATE,CRS_DEP_TIME,DEP_TIME,DEP_DELAY,ARR_TIME,ARR_DELAY,CANCELLED,DISTANCE,CRS_DEP_TIME,CRS_ARR_TIME,TAXI_IN,TAXI_OUT,FL_DATE
count,191095,191095.000000,191095.000000,190879.000000,190937.000000,190442.000000,191095.0,191095.000000,191095.000000,191095.000000,190937.000000,191095.000000,191095
mean,2018-01-05 21:10:18.911012608,1331.356367,1343.168382,14.554964,1475.713335,8.130717,0.0,804.405605,1331.356367,1491.277694,7.730482,17.475439,2018-01-05 21:10:18.911012608
min,2018-01-01 00:00:00,1.000000,1.000000,-49.000000,1.000000,-78.000000,0.0,31.000000,1.000000,1.000000,1.000000,1.000000,2018-01-01 00:00:00
25%,2018-01-03 00:00:00,918.000000,926.000000,-5.000000,1058.000000,-14.000000,0.0,363.000000,918.000000,1105.000000,4.000000,11.000000,2018-01-03 00:00:00
50%,2018-01-06 00:00:00,1325.000000,1335.000000,-1.000000,1515.000000,-5.000000,0.0,641.000000,1325.000000,1520.000000,6.000000,15.000000,2018-01-06 00:00:00
75%,2018-01-09 00:00:00,1735.000000,1748.000000,13.000000,1920.000000,11.000000,0.0,1042.000000,1735.000000,1920.000000,9.000000,20.000000,2018-01-09 00:00:00
max,2018-01-11 00:00:00,2359.000000,2400.000000,1752.000000,2400.000000,1778.000000,0.0,4983.000000,2359.000000,2359.000000,258.000000,164.000000,2018-01-11 00:00:00
std,NaN,491.009260,504.269205,52.543457,537.923801,53.965042,0.0,598.828592,491.009260,518.464759,6.494809,9.954633,NaN

In [ ]:
# I used median instead of mean because flight delay data is 
# skewed and contains extreme outliers. Median gives 
# a more robust measure of central tendency.
df['DEP_DELAY'].median()
df['ARR_DELAY'].median()

np.float32(-5.0)

In [24]:
df.duplicated().sum()

np.int64(0)

In [ ]:
# data sampling for 20% data
df_sample=df.sample(frac=0.2,random_state=42)
df_sample.shape

(38219, 16)

In [26]:
df.dtypes

FL_DATE         datetime64[ns]
OP_CARRIER            category
ORIGIN                category
DEST                  category
CRS_DEP_TIME             int64
DEP_TIME               float64
DEP_DELAY              float32
ARR_TIME               float64
ARR_DELAY              float32
CANCELLED              float64
DISTANCE               float64
CRS_DEP_TIME             int64
CRS_ARR_TIME             int64
TAXI_IN                float32
TAXI_OUT               float32
FL_DATE         datetime64[ns]
dtype: object

In [27]:
df.memory_usage(deep=True).sum()/1024**2

np.float64(18.456738471984863)

In [28]:
df['CANCELLED']=df['CANCELLED'].astype('Int8')

In [29]:
df.dtypes

FL_DATE         datetime64[ns]
OP_CARRIER            category
ORIGIN                category
DEST                  category
CRS_DEP_TIME             int64
DEP_TIME               float64
DEP_DELAY              float32
ARR_TIME               float64
ARR_DELAY              float32
CANCELLED                 Int8
DISTANCE               float64
CRS_DEP_TIME             int64
CRS_ARR_TIME             int64
TAXI_IN                float32
TAXI_OUT               float32
FL_DATE         datetime64[ns]
dtype: object

In [ ]:
# week-2 Analysis and feature analisis 
# flights are cancelled usually having missing delay/taxitimes taking consistant data before feature engineering
# Fill delay columns with median
delay_cols = ['DEP_DELAY', 'ARR_DELAY', 'TAXI_IN', 'TAXI_OUT']

for col in delay_cols:
    df.loc[:, col] = df[col].fillna(df[col].median())

# For cancelled flights, ensure delay = 0 if cancelled
df.loc[df['CANCELLED'] == 1, ['DEP_DELAY', 'ARR_DELAY']] = 0

In [31]:
(df.isnull().sum() / len(df)) * 100

FL_DATE         0.000000
OP_CARRIER      0.000000
ORIGIN          0.000000
DEST            0.000000
CRS_DEP_TIME    0.000000
DEP_TIME        0.000000
DEP_DELAY       0.000000
ARR_TIME        0.082681
ARR_DELAY       0.000000
CANCELLED       0.000000
DISTANCE        0.000000
CRS_DEP_TIME    0.000000
CRS_ARR_TIME    0.000000
TAXI_IN         0.000000
TAXI_OUT        0.000000
FL_DATE         0.000000
dtype: float64

In [32]:
df['FL_DATE']=pd.to_datetime(df['FL_DATE'])

In [33]:
df.dtypes

FL_DATE         datetime64[ns]
OP_CARRIER            category
ORIGIN                category
DEST                  category
CRS_DEP_TIME             int64
DEP_TIME               float64
DEP_DELAY              float32
ARR_TIME               float64
ARR_DELAY              float32
CANCELLED                 Int8
DISTANCE               float64
CRS_DEP_TIME             int64
CRS_ARR_TIME             int64
TAXI_IN                float32
TAXI_OUT               float32
FL_DATE         datetime64[ns]
dtype: object

In [ ]:
# month deriving features
df['MONTH']=df['FL_DATE'].dt.month

In [ ]:
# day of week(number) like 0=mon,6=sun
df['DAY_OF_WEEK'] = df['FL_DATE'].dt.dayofweek

In [ ]:
# day name(better for visualization)
df['DAY_NAME'] = df['FL_DATE'].dt.day_name()

In [37]:
df.columns #duplicate cols have in that df
# df['DEP_HOUR'] = (df['CRS_DEP_TIME'] // 100).astype(int)

Index(['FL_DATE', 'OP_CARRIER', 'ORIGIN', 'DEST', 'CRS_DEP_TIME', 'DEP_TIME',
       'DEP_DELAY', 'ARR_TIME', 'ARR_DELAY', 'CANCELLED', 'DISTANCE',
       'CRS_DEP_TIME', 'CRS_ARR_TIME', 'TAXI_IN', 'TAXI_OUT', 'FL_DATE ',
       'MONTH', 'DAY_OF_WEEK', 'DAY_NAME'],
      dtype='object')

In [ ]:
# removing the duplicate columns
df = df.loc[:, ~df.columns.duplicated()]

In [39]:
df.columns

Index(['FL_DATE', 'OP_CARRIER', 'ORIGIN', 'DEST', 'CRS_DEP_TIME', 'DEP_TIME',
       'DEP_DELAY', 'ARR_TIME', 'ARR_DELAY', 'CANCELLED', 'DISTANCE',
       'CRS_ARR_TIME', 'TAXI_IN', 'TAXI_OUT', 'FL_DATE ', 'MONTH',
       'DAY_OF_WEEK', 'DAY_NAME'],
      dtype='object')

In [ ]:
# departure hour,CRS_DEP_TIME hhmm format extracting hh hours
df['DEP_HOUR'] = (df['CRS_DEP_TIME'] // 100).astype(int)

In [ ]:
# extracting routes like below columns 
df['ROUTE'] = df['ORIGIN'].astype(str) + '-' + df['DEST'].astype(str)

In [43]:
df[['ORIGIN', 'DEST', 'ROUTE']].head()

  ORIGIN DEST    ROUTE
0    EWR  DEN  EWR-DEN
1    LAS  SFO  LAS-SFO
2    SNA  DEN  SNA-DEN
3    RSW  ORD  RSW-ORD
4    ORD  ALB  ORD-ALB

In [ ]:
# checking feature engineering columns
df[['FL_DATE','MONTH','DAY_OF_WEEK','DAY_NAME','DEP_HOUR','ROUTE']].head()

     FL_DATE  MONTH  DAY_OF_WEEK DAY_NAME  DEP_HOUR    ROUTE
0 2018-01-01      1            0   Monday        15  EWR-DEN
1 2018-01-01      1            0   Monday        11  LAS-SFO
2 2018-01-01      1            0   Monday        13  SNA-DEN
3 2018-01-01      1            0   Monday        15  RSW-ORD
4 2018-01-01      1            0   Monday         6  ORD-ALB

In [ ]:
# converting datatypes
df['MONTH'] = df['MONTH'].astype('int8')
df['DAY_OF_WEEK'] = df['DAY_OF_WEEK'].astype('int8')
df['DEP_HOUR'] = df['DEP_HOUR'].astype('int8')
df['DAY_NAME'] = df['DAY_NAME'].astype('category')
df['ROUTE'] = df['ROUTE'].astype('category')

In [46]:
df.memory_usage(deep=True).sum()/1024**2

np.float64(17.40398597717285)

In [47]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 191095 entries, 0 to 199999
Data columns (total 20 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   FL_DATE       191095 non-null  datetime64[ns]
 1   OP_CARRIER    191095 non-null  category
 2   ORIGIN        191095 non-null  category
 3   DEST          191095 non-null  category
 4   CRS_DEP_TIME  191095 non-null  int64
 5   DEP_TIME      191095 non-null  float64
 6   DEP_DELAY     191095 non-null  float32
 7   ARR_TIME      190937 non-null  float64
 8   ARR_DELAY     191095 non-null  float32
 9   CANCELLED     191095 non-null  Int8
 10  DISTANCE      191095 non-null  float64
 11  CRS_ARR_TIME  191095 non-null  int64
 12  TAXI_IN       191095 non-null  float32
 13  TAXI_OUT      191095 non-null  float32
 14  FL_DATE       191095 non-null  datetime64[ns]
 15  MONTH         191095 non-null  int8
 16  DAY_OF_WEEK   191095 non-null  int8
 17  DAY_NAME      191095 non-null  category
 18  DEP_HOUR      191095 non-null  int8
 19  ROUTE         191095 non-null  category
dtypes: Int8(1), category(5), datetime64[ns](2), float32(4), float64(3), int64(2), int8(3)
memory usage: 17.1 MB

In [ ]:
# df.to_csv('Data/Processed/flights_2018_processed.csv', index=False)
import os 
# changed directories
os.chdir("..")

In [ ]:
print(os.getcwd())

c:\Users\fouzi\OneDrive\Desktop\AirFly-Insights

In [ ]:
# saving the processes file or cleaned dataset
df.to_csv('Data/Processed/flights_2018_processed.csv', index=False)

In [56]:
df_check = pd.read_csv('Data/Processed/flights_2018_processed.csv')
df_check.shape

(191095, 20)

In [57]:
import os
os.path.exists('Data/Processed/flights_2018_processed.csv')

True